#ifndef CONSTANTS_H
# define CONSTANTS_H

# include <SDL2/SDL.h>

const unsigned int WINDOW_WIDTH = 800;
const unsigned int WINDOW_HEIGHT = 600;

const unsigned int FPS = 60;
const unsigned int FRAME_TARGET_TIME = 1000 / FPS;

enum CollisionType
{
    NO_COLLISION,
    PLAYER_ENEMY_COLLISION,
    PLAYER_PROJECTILE_COLLISION,
    ENEMY_PROJECTILE_COLLISION,
    PLAYER_VEGETATION_COLLISION,
    PLAYER_LEVEL_COMPLETE_COLLISION
};

enum LayerType
{
	TILEMAP_LAYER,
	VEGETATION_LAYER,
	OBSTACLE_LAYER,
	ENEMY_LAYER,
	PLAYER_LAYER,
	PROJECTILE_LAYER,
	UI_LAYER
}; const unsigned int NUM_LAYER = 7;

const SDL_Color WHITE_COLOR = {255, 255, 255, 255};
const SDL_Color GREEN_COLOR = {0, 255, 0, 255};

#endif
